services:
 mock-pismo-service:
    build: ./
    container_name: mock-pismo-service
    restart: always
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge